//! Source provenance for the generated output.
//!
//! `ROADMAP.md` §10.1 requires it of the real pipeline — *"Provenance maps generated declarations
//! and code spans to source forms, catalog entries, provider selections, and relevant
//! assumptions"* — and §12 S0 requires a first instalment of it at the gate: *"failure points have
//! useful diagnostics and **basic source provenance**"*.
//!
//! # What makes a provenance record worth anything
//!
//! Not that it exists. A record that names a line which does not contain what it claims is worse
//! than none, because it sends a reader somewhere confidently wrong. So this format is built to
//! be **checkable from both ends**, and `S0.5`'s tests check it from both:
//!
//! * every `generated.line` is a real line of the emitted file, and it contains the declaration
//!   the record is about;
//! * every `source.span` is a real span of the description, and the bytes it covers contain the
//!   name the record is about.
//!
//! # Why JSON, hand-written
//!
//! §10.3 already fixes one machine-readable artifact as JSON (`trust-dependencies.json`), so the
//! format has precedent, and the engine carries no dependencies
//! (`docs/decisions/decision_zero-dependency-engine-core.md`). The writer below is therefore
//! deliberately small: flat records, one escaping routine, and a test for the characters that
//! break naive escaping. It is a **writer**, not a serialization library, and it should not grow
//! into one — the moment a second artifact needs JSON, the right move is to review that decision
//! rather than to widen this file.
//!
//! ⚠️ `realization` is a **stub of a §9 catalog entry**, not one. §9 requires an ID, semantic
//! version, content hash, source/license metadata, maintainer, dependencies, supported profiles,
//! preconditions, guarantees, implementation source, model source, cost evidence and evidence
//! status. This carries four of those fields and says so in the artifact itself, because a record
//! that looks like a catalog entry is one somebody will eventually cite as if it were one.

use std::fmt::Write as _;

use eadl_front::{SourceMap, Span};

use crate::interpret::Plan;

/// The format identifier written into every artifact. A consumer that does not recognize it must
/// refuse rather than guess, so it is versioned from the first release.
pub const FORMAT: &str = "archogen-provenance/1";

/// The single fixed S0 realization, as a stub catalog entry.
pub const REALIZATION_ID: &str = "s0.hosted-playground.periodic";
/// Its version. Bumped when the observation contract changes, because every frozen expectation
/// in `examples/s0-heartbeat/expected/` is only valid for one contract.
pub const REALIZATION_VERSION: &str = "0.1.0";

/// One generated declaration and where it came from.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Record {
    /// What kind of declaration this is, e.g. `task`.
    pub declaration: &'static str,
    /// The name it carries in the description, e.g. `beat`.
    pub name: String,
    /// The file it was generated into, relative to the output directory.
    pub generated_file: &'static str,
    /// Its 1-based line in that file.
    pub generated_line: usize,
    /// The source form it came from.
    pub span: Span,
    /// The engine rule that produced it — the "catalog entry" half of §10.1's mapping.
    pub via: &'static str,
}

/// Render the provenance artifact.
///
/// # Panics
///
/// Never: every span in a [`Plan`] came from a source that is in `sources`, and a plan is only
/// built from a description that was read.
#[must_use]
pub fn render(plan: &Plan, records: &[Record], sources: &SourceMap) -> String {
    let source = sources
        .get(plan.span.source)
        .expect("the plan's description is in the source map");

    let mut out = String::new();
    out.push_str("{\n");
    let _ = writeln!(out, "  \"format\": {},", quote(FORMAT));
    out.push_str("  \"experimental\": true,\n");
    out.push_str(
        "  \"note\": \"Generated by the ROADMAP.md §12 S0 prototype. Carries no timing, \
         assurance or OS-completeness claim; `realization` below is a stub of a §9 catalog \
         entry, not one.\",\n",
    );
    let _ = writeln!(out, "  \"description\": {},", quote(&source.name));
    let _ = writeln!(out, "  \"system\": {},", quote(&plan.name));
    let _ = writeln!(out, "  \"hyperperiod_ms\": {},", plan.horizon_ms);
    out.push_str("  \"realization\": {\n");
    let _ = writeln!(out, "    \"id\": {},", quote(REALIZATION_ID));
    let _ = writeln!(out, "    \"version\": {},", quote(REALIZATION_VERSION));
    out.push_str(
        "    \"summary\": \"one hyperperiod of modeled time on the hosted playground; one \
         release event per task release\",\n",
    );
    out.push_str("    \"retired_by\": \"M4.3\",\n");
    out.push_str(
        "    \"catalog_fields_missing\": \"content hash, source/license metadata, maintainer, \
         dependencies, preconditions, guarantees, cost evidence, evidence status (§9)\"\n",
    );
    out.push_str("  },\n");
    out.push_str("  \"records\": [\n");
    for (index, record) in records.iter().enumerate() {
        let position = source.position(record.span.start);
        out.push_str("    {\n");
        let _ = writeln!(out, "      \"declaration\": {},", quote(record.declaration));
        let _ = writeln!(out, "      \"name\": {},", quote(&record.name));
        let _ = writeln!(
            out,
            "      \"generated\": {{ \"file\": {}, \"line\": {} }},",
            quote(record.generated_file),
            record.generated_line
        );
        let _ = writeln!(
            out,
            "      \"source\": {{ \"line\": {}, \"column\": {}, \"start\": {}, \"end\": {} }},",
            position.line, position.column, record.span.start, record.span.end
        );
        let _ = writeln!(out, "      \"via\": {}", quote(record.via));
        out.push_str(if index + 1 == records.len() {
            "    }\n"
        } else {
            "    },\n"
        });
    }
    out.push_str("  ]\n}\n");
    out
}

/// A JSON string literal.
///
/// Escapes the two characters JSON requires (`"` and `\`), the five with short forms, and every
/// remaining control character as `\u00XX`. ⛔ The last clause is the one naive escapers omit: a
/// raw control byte inside a string is invalid JSON, and a file name can contain one.
fn quote(text: &str) -> String {
    let mut out = String::with_capacity(text.len() + 2);
    out.push('"');
    for ch in text.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\u{8}' => out.push_str("\\b"),
            '\u{c}' => out.push_str("\\f"),
            c if (c as u32) < 0x20 => {
                let _ = write!(out, "\\u{:04x}", c as u32);
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::quote;

    #[test]
    fn quoting_escapes_what_json_requires() {
        assert_eq!(quote("plain"), "\"plain\"");
        assert_eq!(quote("a\"b"), "\"a\\\"b\"");
        assert_eq!(quote("a\\b"), "\"a\\\\b\"");
        assert_eq!(quote("a\nb\tc\rd"), "\"a\\nb\\tc\\rd\"");
    }

    #[test]
    fn quoting_escapes_the_control_characters_naive_escapers_miss() {
        // A raw control byte inside a string is invalid JSON, and a path can contain one.
        assert_eq!(quote("a\u{1}b"), "\"a\\u0001b\"");
        assert_eq!(quote("\u{8}\u{c}"), "\"\\b\\f\"");
        assert_eq!(quote("\u{1f}"), "\"\\u001f\"");
    }

    #[test]
    fn quoting_leaves_non_ascii_alone() {
        // JSON is UTF-8; escaping these would be correct but unreadable, and a path is a thing
        // people have to recognize.
        assert_eq!(quote("héllo — ok"), "\"héllo — ok\"");
    }
}
