//! The generated-source marker (leaf `M3.6.6.1`; `docs/specs/trust/decision_trust-generated-sources.md` §3): the rule
//! that says whether a file declares, in its header, that a generator wrote it — stated as code, with its corpus,
//! because two rounds of prose left cases two readers would decide differently.
//!
//! **The header** is the text of the comments that come before the file's first character that is neither whitespace
//! nor inside a comment. Comment syntax is the file's language's, by its extension or name ([`syntax`]); a file with
//! none, or that is not UTF-8 once a byte-order mark is dropped, has no header and is never marked. A `#!` first line
//! is a comment where `#` is, and in Rust unless it opens an attribute (`#![`). Block comments nest in Rust and in no
//! other language here. **Marked** means the header holds one of [`MARKERS`], in any case.

/// The phrases that mark a header, compared without regard to case.
pub const MARKERS: &[&str] = &[
    "@generated",
    "do not edit",
    "automatically generated",
    "auto-generated",
    "autogenerated",
    "generated by",
];

/// A language's comment syntax, as far as the header needs it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Syntax {
    /// `//` lines and `/* */` blocks; Rust's nest.
    Slash {
        /// Whether a `/*` inside a block opens another.
        nests: bool,
    },
    /// `#` lines.
    Hash,
    /// `;` lines.
    Semicolon,
    /// `--` lines.
    Dash,
    /// `<!-- -->` blocks.
    Angle,
    /// No comment syntax: never marked.
    None,
}

/// The comment syntax of the file at `path`, by its extension, or for a file with none by its name.
#[must_use]
pub fn syntax(path: &str) -> Syntax {
    let name = path.rsplit('/').next().unwrap_or(path);
    let ext = name
        .rsplit_once('.')
        .map_or("", |(_, e)| e)
        .to_ascii_lowercase();
    match ext.as_str() {
        "rs" => Syntax::Slash { nests: true },
        "c" | "h" | "cc" | "cpp" | "cxx" | "hpp" | "js" | "ts" | "go" | "java" | "kt" | "swift"
        | "scala" | "proto" | "css" => Syntax::Slash { nests: false },
        "sh" | "bash" | "zsh" | "py" | "rb" | "pl" | "toml" | "yml" | "yaml" | "cmake" | "mk"
        | "r" | "env" | "conf" => Syntax::Hash,
        "eadl" | "el" | "lisp" | "clj" | "s" | "asm" | "ini" => Syntax::Semicolon,
        "sql" | "lua" | "hs" | "ada" | "vhd" | "vhdl" => Syntax::Dash,
        "md" | "html" | "htm" | "xml" | "svg" => Syntax::Angle,
        "" if matches!(name, "Makefile" | "makefile" | "GNUmakefile" | "Dockerfile") => {
            Syntax::Hash
        }
        _ => Syntax::None,
    }
}

/// The header's comment text, or `None` when the file has no comment syntax or is not UTF-8.
#[must_use]
pub fn header(path: &str, bytes: &[u8]) -> Option<String> {
    let syn = syntax(path);
    if syn == Syntax::None {
        return None;
    }
    let text = std::str::from_utf8(bytes).ok()?;
    let text = text.strip_prefix('\u{feff}').unwrap_or(text);
    let s: Vec<char> = text.chars().collect();
    let (mut i, mut out) = (0usize, String::new());
    let at = |i: usize, pat: &str| -> bool {
        pat.chars()
            .enumerate()
            .all(|(k, c)| s.get(i + k) == Some(&c))
    };
    let line = |i: &mut usize, out: &mut String| {
        while *i < s.len() && s[*i] != '\n' {
            out.push(s[*i]);
            *i += 1;
        }
        out.push('\n');
    };
    // A `#!` first line.
    if at(0, "#!")
        && (syn == Syntax::Hash || (matches!(syn, Syntax::Slash { nests: true }) && !at(0, "#![")))
    {
        line(&mut i, &mut out);
    }
    loop {
        while i < s.len() && s[i].is_whitespace() {
            i += 1;
        }
        if i >= s.len() {
            break;
        }
        match syn {
            Syntax::Slash { nests } => {
                if at(i, "//") {
                    line(&mut i, &mut out);
                } else if at(i, "/*") {
                    i += 2;
                    let mut depth = 1usize;
                    while i < s.len() && depth > 0 {
                        if nests && at(i, "/*") {
                            depth += 1;
                            out.push_str("/*");
                            i += 2;
                        } else if at(i, "*/") {
                            depth -= 1;
                            i += 2;
                        } else {
                            out.push(s[i]);
                            i += 1;
                        }
                    }
                    out.push('\n');
                } else {
                    break;
                }
            }
            Syntax::Hash if at(i, "#") => line(&mut i, &mut out),
            Syntax::Semicolon if at(i, ";") => line(&mut i, &mut out),
            Syntax::Dash if at(i, "--") => line(&mut i, &mut out),
            Syntax::Angle if at(i, "<!--") => {
                i += 4;
                while i < s.len() && !at(i, "-->") {
                    out.push(s[i]);
                    i += 1;
                }
                i += 3;
                out.push('\n');
            }
            _ => break,
        }
    }
    Some(out)
}

/// Whether the file at `path` is marked as generated: its header holds one of [`MARKERS`], in any case.
#[must_use]
pub fn marked(path: &str, bytes: &[u8]) -> bool {
    header(path, bytes).is_some_and(|h| {
        let h = h.to_lowercase();
        MARKERS.iter().any(|m| h.contains(m))
    })
}

#[cfg(test)]
mod tests {
    //! The corpus: every case the record's two review rounds raised, each with the outcome the rule gives it.

    use super::marked;

    #[test]
    fn the_corpus() {
        let licence = "// licence text, one of many lines\n".repeat(30);
        let long = format!("{licence}// @generated\nfn f() {{}}\n");
        let cases: &[(&str, &[u8], bool, &str)] = &[
            (
                "x.rs",
                b"// @generated by gen.sh\nfn f() {}\n",
                true,
                "a line comment",
            ),
            (
                "x.rs",
                "\u{feff}// @generated\nfn f() {}\n".as_bytes(),
                true,
                "a byte-order mark is dropped",
            ),
            (
                "x.rs",
                b"// Code generated by x. DO NOT EDIT.\r\nfn f() {}\r\n",
                true,
                "CRLF line endings",
            ),
            (
                "x.rs",
                b"/*\n   Code generated by scripts/gen.sh. DO NOT EDIT.\n*/\nfn f() {}\n",
                true,
                "a block comment's inner line",
            ),
            (
                "x.rs",
                long.as_bytes(),
                true,
                "a marker below a long licence comment",
            ),
            (
                "x.rs",
                b"fn f() {} // @generated\n",
                false,
                "a trailing comment on a code line",
            ),
            (
                "x.rs",
                b"const S: &str = \"generated by archogen\";\n",
                false,
                "a string",
            ),
            (
                "x.rs",
                b"fn f() {}\n// @generated\n",
                false,
                "a body marker",
            ),
            (
                "t.bin",
                &[0xff, 0xfe, 0x00, 0x40, 0x67],
                false,
                "a binary file: no comment syntax",
            ),
            (
                "x.rs",
                &[0x2f, 0x2f, 0x20, 0xff, 0xfe, 0x0a],
                false,
                "not UTF-8: never marked",
            ),
            (
                "x.rs",
                b"#![allow(dead_code)]\n// @generated\n",
                false,
                "an attribute is code and ends the header",
            ),
            (
                "x.rs",
                b"# [derive(Debug)]\n// @generated\n",
                false,
                "a spaced attribute too",
            ),
            (
                "x.rs",
                b"#!/usr/bin/env run-cargo-script\n// @generated\n",
                true,
                "a shebang in Rust",
            ),
            (
                "x.sh",
                b"#!/bin/sh\n# generated by gen.py\necho\n",
                true,
                "a shebang and a hash comment",
            ),
            (
                "x.rs",
                b"/* outer /* inner */ still a comment: @generated */\nfn f() {}\n",
                true,
                "Rust's blocks nest",
            ),
            (
                "x.c",
                b"/* a /* b */ code @generated */\nint x;\n",
                false,
                "C's close at the first */",
            ),
            (
                "x.rs",
                b"/* x */ fn f() {} // @generated\n",
                false,
                "code after a block on its line",
            ),
            (
                "x.rs",
                b"// see /* no block opens here\n@generated\n",
                false,
                "a /* inside a line comment opens nothing",
            ),
            (
                "x.md",
                b"# Title\n<!-- generated by x -->\n",
                false,
                "a Markdown heading is content",
            ),
            (
                "x.md",
                b"<!-- generated by x -->\n# Title\n",
                true,
                "an HTML comment first",
            ),
            (
                "x.h",
                b"#ifndef X\n// generated by y\n",
                false,
                "a preprocessor line is code in C",
            ),
            (
                "x.csv",
                b"# generated by x\n1,2\n",
                false,
                "a CSV has no comment syntax",
            ),
            (
                "x.eadl",
                b"; generated by the tool\n(defblock b)\n",
                true,
                "an eADL comment",
            ),
            ("x.rs", b"// AUTO-GENERATED file\n", true, "any case"),
            ("x.rs", b"// Do Not Edit\n", true, "any case, do not edit"),
            ("x.rs", b"", false, "an empty file"),
            ("x.rs", b"  \n\n", false, "whitespace alone"),
            (
                "x.rs",
                b"// @generated",
                true,
                "a header that is the whole file, no newline",
            ),
            (
                "Makefile",
                b"# generated by cmake\nall:\n",
                true,
                "a Makefile, by its name",
            ),
            (
                "x.py",
                b"\n\n# autogenerated from schema.json\nimport x\n",
                true,
                "blank lines before the header",
            ),
        ];
        for (path, bytes, want, why) in cases {
            assert_eq!(marked(path, bytes), *want, "{why}: {path}");
        }
    }
}
