//! The generated-source marker (leaf `M3.6.6.1`; `docs/specs/trust/decision_trust-generated-sources.md` §3): the rule
//! that says whether a file declares, in its header, that a generator wrote it — stated as code, with its corpus,
//! because two rounds of prose left cases two readers would decide differently.
//!
//! **The header** is the text of the comments that come before the file's first character that is neither whitespace
//! nor inside a comment. Comment syntax is the file's language's, by its extension or name ([`syntax`]); a file with
//! none, or that is not UTF-8 once a byte-order mark is dropped, has no header and is never marked; a file with no
//! extension whose first line is a `#!` is read with `#` comments. A `#!` first line is a comment where `#` is, and in
//! Rust unless what follows it, comments and whitespace aside, is `[` — an inner attribute, as rustc 1.95.0 reads
//! it (measured `2026-10-06`, the generated-sources record §3). Block comments nest in Rust, Kotlin, Swift and Scala, and in no other language here; an unclosed block
//! runs to the end of the file. A line ends at `\n` or `\r`. An XML declaration (`<?xml … ?>`) may come before the
//! comments of an `<!-- -->` file. **Marked** means the header holds one of [`MARKERS`], in any case.

/// The phrases that mark a header, compared without regard to case.
pub const MARKERS: &[&str] = &[
    "@generated",
    "do not edit",
    "automatically generated",
    "auto-generated",
    "autogenerated",
    "generated by",
];

/// A language's comment syntax, as far as the header needs it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Syntax {
    /// `//` lines and `/* */` blocks; Rust's nest.
    Slash {
        /// Whether a `/*` inside a block opens another.
        nests: bool,
    },
    /// `/* */` blocks alone, not nesting (CSS).
    Block,
    /// `#` lines.
    Hash,
    /// `;` lines.
    Semicolon,
    /// `--` lines.
    Dash,
    /// `<!-- -->` blocks.
    Angle,
    /// No comment syntax: never marked.
    None,
}

/// The extensions and the file names each syntax is read for: the whole of the recogniser's reach. §3 of the
/// generated-sources record holds the same table, machine-read, and a test holds the two equal.
pub const TABLE: &[(Syntax, &[&str], &[&str])] = &[
    (
        Syntax::Slash { nests: true },
        &["rs", "kt", "swift", "scala"],
        &[],
    ),
    (
        Syntax::Slash { nests: false },
        &[
            "c", "h", "cc", "cpp", "cxx", "hh", "hpp", "hxx", "js", "ts", "go", "java", "proto",
        ],
        &[],
    ),
    (Syntax::Block, &["css"], &[]),
    (
        Syntax::Hash,
        &[
            "sh", "bash", "zsh", "py", "rb", "pl", "r", "toml", "yml", "yaml", "cmake", "mk",
            "env", "conf",
        ],
        &[
            "Makefile",
            "makefile",
            "GNUmakefile",
            "Dockerfile",
            "CMakeLists.txt",
        ],
    ),
    (
        Syntax::Semicolon,
        &["eadl", "el", "lisp", "clj", "s", "asm", "ini"],
        &[],
    ),
    (
        Syntax::Dash,
        &["sql", "lua", "hs", "ada", "adb", "ads", "vhd", "vhdl"],
        &[],
    ),
    (Syntax::Angle, &["md", "html", "htm", "xml", "svg"], &[]),
];

/// The comment syntax of the file at `path`: by its exact name first, then by its extension in any case.
#[must_use]
pub fn syntax(path: &str) -> Syntax {
    let name = path.rsplit('/').next().unwrap_or(path);
    let ext = name
        .rsplit_once('.')
        .map_or(String::new(), |(_, e)| e.to_ascii_lowercase());
    TABLE
        .iter()
        .find(|(_, _, names)| names.contains(&name))
        .or_else(|| {
            TABLE
                .iter()
                .find(|(_, exts, _)| !ext.is_empty() && exts.contains(&ext.as_str()))
        })
        .map_or(Syntax::None, |(syn, _, _)| *syn)
}

/// The header's comment text, or `None` when the file has no comment syntax or is not UTF-8.
#[must_use]
pub fn header(path: &str, bytes: &[u8]) -> Option<String> {
    let name = path.rsplit('/').next().unwrap_or(path);
    let syn = match syntax(path) {
        Syntax::None if !name.contains('.') && bytes.starts_with(b"#!") => Syntax::Hash,
        other => other,
    };
    if syn == Syntax::None {
        return None;
    }
    let text = std::str::from_utf8(bytes).ok()?;
    let text = text.strip_prefix('\u{feff}').unwrap_or(text);
    let s: Vec<char> = text.chars().collect();
    let (mut i, mut out) = (0usize, String::new());
    let at = |i: usize, pat: &str| -> bool {
        pat.chars()
            .enumerate()
            .all(|(k, c)| s.get(i + k) == Some(&c))
    };
    let line = |i: &mut usize, out: &mut String| {
        while *i < s.len() && s[*i] != '\n' && s[*i] != '\r' {
            out.push(s[*i]);
            *i += 1;
        }
        out.push('\n');
    };
    // A `#!` first line: a comment where `#` is; in Rust a shebang unless `[` follows, whitespace and comments aside —
    // block comments nesting, a line comment ending at a line feed, and a doc comment (`///` but not `////`, `//!`,
    // `/**` but not `/**/` or `/***`, `/*!`) ending the look-ahead: measured on rustc 1.95.0 (the record's §3).
    let rust_attribute = || {
        let mut j = 2;
        loop {
            while j < s.len() && s[j].is_whitespace() {
                j += 1;
            }
            let doc = (at(j, "///") && !at(j, "////"))
                || at(j, "//!")
                || (at(j, "/**") && !at(j, "/**/") && !at(j, "/***"))
                || at(j, "/*!");
            if doc {
                return false;
            }
            if at(j, "//") {
                while j < s.len() && s[j] != '\n' {
                    j += 1;
                }
            } else if at(j, "/*") {
                j += 2;
                let mut depth = 1usize;
                while j < s.len() && depth > 0 {
                    if at(j, "/*") {
                        depth += 1;
                        j += 2;
                    } else if at(j, "*/") {
                        depth -= 1;
                        j += 2;
                    } else {
                        j += 1;
                    }
                }
            } else {
                return s.get(j) == Some(&'[');
            }
        }
    };
    let is_rust = path.to_ascii_lowercase().ends_with(".rs");
    if at(0, "#!") && (syn == Syntax::Hash || (is_rust && !rust_attribute())) {
        line(&mut i, &mut out);
    }
    // An XML declaration before an `<!-- -->` file's comments.
    if syn == Syntax::Angle {
        let mut j = 0;
        while j < s.len() && s[j].is_whitespace() {
            j += 1;
        }
        if at(j, "<?") {
            while j < s.len() && !at(j, "?>") {
                j += 1;
            }
            i = j + 2;
        }
    }
    loop {
        while i < s.len() && s[i].is_whitespace() {
            i += 1;
        }
        if i >= s.len() {
            break;
        }
        match syn {
            Syntax::Slash { nests } => {
                if at(i, "//") {
                    line(&mut i, &mut out);
                } else if at(i, "/*") {
                    i += 2;
                    let mut depth = 1usize;
                    while i < s.len() && depth > 0 {
                        if nests && at(i, "/*") {
                            depth += 1;
                            out.push_str("/*");
                            i += 2;
                        } else if at(i, "*/") {
                            depth -= 1;
                            i += 2;
                        } else {
                            out.push(s[i]);
                            i += 1;
                        }
                    }
                    out.push('\n');
                } else {
                    break;
                }
            }
            Syntax::Block if at(i, "/*") => {
                i += 2;
                while i < s.len() && !at(i, "*/") {
                    out.push(s[i]);
                    i += 1;
                }
                i += 2;
                out.push('\n');
            }
            Syntax::Hash if at(i, "#") => line(&mut i, &mut out),
            Syntax::Semicolon if at(i, ";") => line(&mut i, &mut out),
            Syntax::Dash if at(i, "--") => line(&mut i, &mut out),
            Syntax::Angle if at(i, "<!--") => {
                i += 4;
                while i < s.len() && !at(i, "-->") {
                    out.push(s[i]);
                    i += 1;
                }
                i += 3;
                out.push('\n');
            }
            _ => break,
        }
    }
    Some(out)
}

/// Whether the file at `path` is marked as generated: its header holds one of [`MARKERS`], in any case.
#[must_use]
pub fn marked(path: &str, bytes: &[u8]) -> bool {
    header(path, bytes).is_some_and(|h| {
        let h = h.to_lowercase();
        MARKERS.iter().any(|m| h.contains(m))
    })
}

#[cfg(test)]
mod tests {
    //! The corpus: every case the record's review rounds raised, each with the outcome the rule gives it; and the
    //! record's machine-read table of comment syntax, held equal to [`super::TABLE`].

    use super::marked;

    #[test]
    fn the_corpus() {
        let licence = "// licence text, one of many lines\n".repeat(30);
        let long = format!("{licence}// @generated\nfn f() {{}}\n");
        let cases: &[(&str, &[u8], bool, &str)] = &[
            (
                "x.rs",
                b"// @generated by gen.sh\nfn f() {}\n",
                true,
                "a line comment",
            ),
            (
                "x.rs",
                "\u{feff}// @generated\nfn f() {}\n".as_bytes(),
                true,
                "a byte-order mark is dropped",
            ),
            (
                "x.rs",
                b"// Code generated by x. DO NOT EDIT.\r\nfn f() {}\r\n",
                true,
                "CRLF line endings",
            ),
            (
                "x.rs",
                b"/*\n   Code generated by scripts/gen.sh. DO NOT EDIT.\n*/\nfn f() {}\n",
                true,
                "a block comment's inner line",
            ),
            (
                "x.rs",
                long.as_bytes(),
                true,
                "a marker below a long licence comment",
            ),
            (
                "x.rs",
                b"fn f() {} // @generated\n",
                false,
                "a trailing comment on a code line",
            ),
            (
                "x.rs",
                b"const S: &str = \"generated by archogen\";\n",
                false,
                "a string",
            ),
            (
                "x.rs",
                b"fn f() {}\n// @generated\n",
                false,
                "a body marker",
            ),
            (
                "t.bin",
                &[0xff, 0xfe, 0x00, 0x40, 0x67],
                false,
                "a binary file: no comment syntax",
            ),
            (
                "x.rs",
                &[0x2f, 0x2f, 0x20, 0xff, 0xfe, 0x0a],
                false,
                "not UTF-8: never marked",
            ),
            (
                "x.rs",
                b"#![allow(dead_code)]\n// @generated\n",
                false,
                "an attribute is code and ends the header",
            ),
            (
                "x.rs",
                b"# [derive(Debug)]\n// @generated\n",
                false,
                "a spaced attribute too",
            ),
            (
                "x.rs",
                b"#!/usr/bin/env run-cargo-script\n// @generated\n",
                true,
                "a shebang in Rust",
            ),
            (
                "x.sh",
                b"#!/bin/sh\n# generated by gen.py\necho\n",
                true,
                "a shebang and a hash comment",
            ),
            (
                "x.rs",
                b"/* outer /* inner */ still a comment: @generated */\nfn f() {}\n",
                true,
                "Rust's blocks nest",
            ),
            (
                "x.c",
                b"/* a /* b */ code @generated */\nint x;\n",
                false,
                "C's close at the first */",
            ),
            (
                "x.rs",
                b"/* x */ fn f() {} // @generated\n",
                false,
                "code after a block on its line",
            ),
            (
                "x.rs",
                b"// see /* no block opens here\n@generated\n",
                false,
                "a /* inside a line comment opens nothing",
            ),
            (
                "x.md",
                b"# Title\n<!-- generated by x -->\n",
                false,
                "a Markdown heading is content",
            ),
            (
                "x.md",
                b"<!-- generated by x -->\n# Title\n",
                true,
                "an HTML comment first",
            ),
            (
                "x.h",
                b"#ifndef X\n// generated by y\n",
                false,
                "a preprocessor line is code in C",
            ),
            (
                "x.csv",
                b"# generated by x\n1,2\n",
                false,
                "a CSV has no comment syntax",
            ),
            (
                "x.eadl",
                b"; generated by the tool\n(defblock b)\n",
                true,
                "an eADL comment",
            ),
            ("x.rs", b"// AUTO-GENERATED file\n", true, "any case"),
            ("x.rs", b"// Do Not Edit\n", true, "any case, do not edit"),
            ("x.rs", b"", false, "an empty file"),
            ("x.rs", b"  \n\n", false, "whitespace alone"),
            (
                "x.rs",
                b"// @generated",
                true,
                "a header that is the whole file, no newline",
            ),
            (
                "Makefile",
                b"# generated by cmake\nall:\n",
                true,
                "a Makefile, by its name",
            ),
            (
                "x.py",
                b"\n\n# autogenerated from schema.json\nimport x\n",
                true,
                "blank lines before the header",
            ),
            (
                "x.rs",
                b"#! [allow(dead_code)]\n// @generated\n",
                false,
                "a spaced inner attribute is no shebang",
            ),
            (
                "x.rs",
                b"#! /* c */ [allow(x)]\n// @generated\n",
                false,
                "nor one after a comment",
            ),
            (
                "x.kt",
                b"/* a /* b */ @generated */\nclass X\n",
                true,
                "Kotlin's blocks nest",
            ),
            (
                "x.py",
                b"# h\rimport x\r# @generated\r",
                false,
                "a CR ends a line, so a body marker stays in the body",
            ),
            (
                "x.xml",
                b"<?xml version=\"1.0\"?>\n<!-- Generated by x -->\n<a/>\n",
                true,
                "an XML declaration first",
            ),
            (
                "scripts/foo",
                b"#!/bin/sh\n# generated by gen.py\necho\n",
                true,
                "an extensionless script by its shebang",
            ),
            (
                "scripts/foo",
                b"generated by nothing\n",
                false,
                "an extensionless file with no shebang",
            ),
            (
                "x.rs",
                b"/* licence\nfn f() {} // @generated\n",
                true,
                "an unclosed block runs to the end",
            ),
            (
                "x.rs",
                b"//! The S0 table, generated by gen.sh.\npub const T: u8 = 1;\n",
                true,
                "an inner doc comment is a comment",
            ),
            ("X.RS", b"// @generated\n", true, "an extension in capitals"),
            (
                "x.rs",
                b"#! /* a /* b */ c */ [allow(dead_code)]\n// @generated\nfn f() {}\n",
                false,
                "the look-ahead nests",
            ),
            (
                "x.rs",
                b"#! /*! d */ [allow(dead_code)]\n// @generated\nfn f() {}\n",
                true,
                "a doc comment ends the look-ahead: a shebang",
            ),
            (
                "x.rs",
                b"#! /// d\n// @generated\n",
                true,
                "a line doc comment too",
            ),
            (
                "x.rs",
                b"#! // c\n[allow(dead_code)]\n// @generated\n",
                false,
                "a plain line comment is skipped",
            ),
            (
                "x.adb",
                b"-- generated by gnatprep\nprocedure P is\n",
                true,
                "Ada's body file",
            ),
            ("x.r", b"# generated by roxygen2\nf <- 1\n", true, "R"),
            (
                "CMakeLists.txt",
                b"# generated by a template\nproject(x)\n",
                true,
                "CMake by its name",
            ),
            (
                "x.css",
                b"// generated by x\na {}\n",
                false,
                "CSS has no line comments",
            ),
            (
                "x.css",
                b"/* generated by x */\na {}\n",
                true,
                "a CSS block comment",
            ),
        ];
        for (path, bytes, want, why) in cases {
            assert_eq!(marked(path, bytes), *want, "{why}: {path}");
        }
    }

    #[test]
    fn the_record_s_table_of_comment_syntax_is_the_code_s() {
        use super::{Syntax, TABLE};
        let record = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../docs/specs/trust/decision_trust-generated-sources.md"),
        )
        .expect("the record");
        let table = record
            .split("<!-- machine-read: comment-syntax -->")
            .nth(1)
            .expect("the record's machine-read table");
        let words = |cell: &str| -> Vec<String> {
            let mut w: Vec<String> = cell
                .split('`')
                .skip(1)
                .step_by(2)
                .map(str::to_owned)
                .collect();
            w.sort();
            w
        };
        let mut rows = Vec::new();
        for line in table.lines().skip(3) {
            let cells: Vec<&str> = line.split('|').map(str::trim).collect();
            if cells.len() < 5 {
                break;
            }
            let syn = match cells[1] {
                "`//` and `/* */`, nesting" => Syntax::Slash { nests: true },
                "`//` and `/* */`" => Syntax::Slash { nests: false },
                "`/* */`" => Syntax::Block,
                "`#`" => Syntax::Hash,
                "`;`" => Syntax::Semicolon,
                "`--`" => Syntax::Dash,
                "`<!-- -->`" => Syntax::Angle,
                other => panic!("a syntax the code does not name: {other}"),
            };
            rows.push((syn, words(cells[2]), words(cells[3])));
        }
        let code: Vec<(Syntax, Vec<String>, Vec<String>)> = TABLE
            .iter()
            .map(|(syn, exts, names)| {
                let sorted = |xs: &[&str]| {
                    let mut v: Vec<String> = xs.iter().map(|x| (*x).to_owned()).collect();
                    v.sort();
                    v
                };
                (*syn, sorted(exts), sorted(names))
            })
            .collect();
        assert_eq!(
            rows, code,
            "the record's §3 table and generated_header::TABLE"
        );
    }
}
