//! The generated-source marker (leaf `M3.6.6.1`; `docs/specs/trust/decision_trust-generated-sources.md` §3): the rule
//! that says whether a file declares, in its header, that a generator wrote it — stated as code, with its corpus,
//! because two rounds of prose left cases two readers would decide differently.
//!
//! **The header** is the text of the comments that come before the file's first character that is neither whitespace
//! nor inside a comment. Comment syntax is the file's language's, by its extension or name ([`syntax`]); a file with
//! none has an empty header and is never marked; a file's bytes are read as UTF-8, an invalid sequence as U+FFFD; a file with no
//! extension whose first line is a `#!` is read with `#` comments. A `#!` first line is a comment where `#` is; in Rust
//! it is one when rustc reads it as a shebang ([`rust_shebang`], held to the pinned rustc by a test), and it then ends
//! at a line feed alone. Block comments nest in Rust, Kotlin, Swift and Scala, and in no other language here; an unclosed block
//! runs to the end of the file. Any other line ends at `\n` or `\r`. An XML declaration (`<?xml … ?>`) may come before the
//! comments of an `<!-- -->` file. **Marked** means the header holds one of [`MARKERS`], in any case.
//!
//! The record states these rules as the rows of a table, each broken by a catalogued mutation (`xtask/mutations.txt`)
//! the corpus or the fixture kills; `scripts/mutation_sweep.sh` holds the rest of its functions, every mutation its
//! operators make killed, timed out or not compiling, or listed, with its reason, in `xtask/generated_header.equivalents`.

/// The phrases that mark a header, compared without regard to case.
pub const MARKERS: &[&str] = &[
    "@generated",
    "do not edit",
    "automatically generated",
    "auto-generated",
    "autogenerated",
    "generated by",
];

/// A language's comment syntax, as far as the header needs it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Syntax {
    /// `//` lines and `/* */` blocks; Rust's, Kotlin's, Swift's and Scala's nest.
    Slash {
        /// Whether a `/*` inside a block opens another.
        nests: bool,
    },
    /// `/* */` blocks alone, not nesting (CSS).
    Block,
    /// `#` lines.
    Hash,
    /// `;` lines.
    Semicolon,
    /// `--` lines.
    Dash,
    /// `<!-- -->` blocks.
    Angle,
    /// No comment syntax: never marked.
    None,
}

/// The extensions and the file names each syntax is read for: the whole of the recogniser's reach. §3 of the
/// generated-sources record and the book's trust chapter hold the same table, machine-read, and a test holds each
/// equal to this one.
pub const TABLE: &[(Syntax, &[&str], &[&str])] = &[
    (
        Syntax::Slash { nests: true },
        &["rs", "kt", "swift", "scala"],
        &[],
    ),
    (
        Syntax::Slash { nests: false },
        &[
            "c", "h", "cc", "cpp", "cxx", "hh", "hpp", "hxx", "js", "ts", "go", "java", "proto",
        ],
        &[],
    ),
    (Syntax::Block, &["css"], &[]),
    (
        Syntax::Hash,
        &[
            "sh", "bash", "zsh", "py", "rb", "pl", "r", "toml", "yml", "yaml", "cmake", "mk",
            "env", "conf",
        ],
        &[
            "Makefile",
            "makefile",
            "GNUmakefile",
            "Dockerfile",
            "CMakeLists.txt",
            ".env",
        ],
    ),
    (
        Syntax::Semicolon,
        &["eadl", "el", "lisp", "clj", "s", "asm", "ini"],
        &[],
    ),
    (
        Syntax::Dash,
        &["sql", "lua", "hs", "ada", "adb", "ads", "vhd", "vhdl"],
        &[],
    ),
    (Syntax::Angle, &["md", "html", "htm", "xml", "svg"], &[]),
];

/// A file name's extension: what follows its last `.`, when a `.` comes after its first character and something follows
/// it — so a dotfile such as `.env` has none and is read by its name, and `foo.` has none either.
fn extension(name: &str) -> Option<String> {
    let first = name.chars().next()?;
    let rest = &name[first.len_utf8()..];
    rest.rsplit_once('.')
        .map(|(_, e)| e.to_ascii_lowercase())
        .filter(|e| !e.is_empty())
}

/// The comment syntax of the file at `path`: by its exact name first, then by its extension in any case.
#[must_use]
pub fn syntax(path: &str) -> Syntax {
    let name = path.rsplit('/').next().unwrap_or(path);
    let ext = extension(name).unwrap_or_default();
    TABLE
        .iter()
        .find(|(_, _, names)| names.contains(&name))
        .or_else(|| {
            TABLE
                .iter()
                .find(|(_, exts, _)| !ext.is_empty() && exts.contains(&ext.as_str()))
        })
        .map_or(Syntax::None, |(syn, _, _)| *syn)
}

/// Rust's `Pattern_White_Space`, which rustc's lexer skips between `#!` and `[`.
fn pattern_white_space(c: char) -> bool {
    matches!(
        c,
        '\u{9}'..='\u{d}' | ' ' | '\u{85}' | '\u{200e}' | '\u{200f}' | '\u{2028}' | '\u{2029}'
    )
}

/// Whether rustc reads a Rust file opening `#!` as a shebang: unless what follows the `#!` is `[`, with
/// `Pattern_White_Space` and plain comments skipped — block comments nesting, a line comment ending at a line feed, and
/// `////`, `/**/` and `/***` plain — while a doc comment (`///`, `//!`, `/**`, `/*!`) ends the look-ahead. The
/// test `the_shebang_rule_is_rustc_s` compiles each case with the pinned rustc and holds this to it.
#[must_use]
pub fn rust_shebang(s: &[char]) -> bool {
    let at = |i: usize, pat: &str| -> bool {
        pat.chars()
            .enumerate()
            .all(|(k, c)| s.get(i + k) == Some(&c))
    };
    if !at(0, "#!") {
        return false;
    }
    let mut j = 2;
    loop {
        while j < s.len() && pattern_white_space(s[j]) {
            j += 1;
        }
        let doc = (at(j, "///") && !at(j, "////"))
            || at(j, "//!")
            || (at(j, "/**") && !at(j, "/**/") && !at(j, "/***"))
            || at(j, "/*!");
        if doc {
            return true;
        }
        if at(j, "//") {
            while j < s.len() && s[j] != '\n' {
                j += 1;
            }
        } else if at(j, "/*") {
            j += 2;
            let mut depth = 1usize;
            while j < s.len() && depth > 0 {
                if at(j, "/*") {
                    depth += 1;
                    j += 2;
                } else if at(j, "*/") {
                    depth -= 1;
                    j += 2;
                } else {
                    j += 1;
                }
            }
        } else {
            return s.get(j) != Some(&'[');
        }
    }
}

/// The header's comment text, empty when the file has no comment syntax. Its bytes are read as UTF-8, an invalid
/// sequence as U+FFFD, so one bad byte after a clean header does not hide it.
fn header(path: &str, bytes: &[u8]) -> String {
    let name = path.rsplit('/').next().unwrap_or(path);
    let decoded = String::from_utf8_lossy(bytes);
    let text = decoded.strip_prefix('\u{feff}').unwrap_or(&decoded);
    let syn = match syntax(path) {
        Syntax::None if extension(name).is_none() && text.starts_with("#!") => Syntax::Hash,
        other => other,
    };
    let s: Vec<char> = text.chars().collect();
    let (mut i, mut out) = (0usize, String::new());
    let at = |i: usize, pat: &str| -> bool {
        pat.chars()
            .enumerate()
            .all(|(k, c)| s.get(i + k) == Some(&c))
    };
    let line = |i: &mut usize, out: &mut String| {
        while *i < s.len() && s[*i] != '\n' && s[*i] != '\r' {
            out.push(s[*i]);
            *i += 1;
        }
        out.push('\n');
    };
    // A `#!` first line: in Rust a comment when `rust_shebang` says rustc reads it as a shebang, ending at a line feed as
    // rustc's does. Where `#` is a comment it is one like any `#` line, read by the loop below.
    let is_rust = extension(name).as_deref() == Some("rs");
    if is_rust && rust_shebang(&s) {
        // rustc's shebang ends at a line feed alone.
        while i < s.len() && s[i] != '\n' {
            out.push(s[i]);
            i += 1;
        }
        out.push('\n');
    }
    // An XML declaration before an `<!-- -->` file's comments.
    if syn == Syntax::Angle {
        let mut j = 0;
        while j < s.len() && s[j].is_whitespace() {
            j += 1;
        }
        // The XML declaration alone — `<?xml` and then whitespace or `?` — not any processing instruction.
        if at(j, "<?xml") && s.get(j + 5).is_some_and(|c| c.is_whitespace() || *c == '?') {
            while j < s.len() && !at(j, "?>") {
                j += 1;
            }
            i = j + 2;
        }
    }
    loop {
        while i < s.len() && s[i].is_whitespace() {
            i += 1;
        }
        match syn {
            Syntax::Slash { nests } => {
                if at(i, "//") {
                    line(&mut i, &mut out);
                } else if at(i, "/*") {
                    i += 2;
                    let mut depth = 1usize;
                    while i < s.len() && depth > 0 {
                        // A nested block's delimiters leave the header's text, its own text staying.
                        if nests && at(i, "/*") {
                            depth += 1;
                            i += 2;
                        } else if at(i, "*/") {
                            depth -= 1;
                            i += 2;
                        } else {
                            out.push(s[i]);
                            i += 1;
                        }
                    }
                    out.push('\n');
                } else {
                    break;
                }
            }
            Syntax::Block if at(i, "/*") => {
                i += 2;
                while i < s.len() && !at(i, "*/") {
                    out.push(s[i]);
                    i += 1;
                }
                i += 2;
                out.push('\n');
            }
            Syntax::Hash if at(i, "#") => line(&mut i, &mut out),
            Syntax::Semicolon if at(i, ";") => line(&mut i, &mut out),
            Syntax::Dash if at(i, "--") => line(&mut i, &mut out),
            Syntax::Angle if at(i, "<!--") => {
                i += 4;
                while i < s.len() && !at(i, "-->") {
                    out.push(s[i]);
                    i += 1;
                }
                i += 3;
                out.push('\n');
            }
            _ => break,
        }
    }
    out
}

/// Whether the file at `path` is marked as generated: its header holds one of [`MARKERS`], in any case.
#[must_use]
pub fn marked(path: &str, bytes: &[u8]) -> bool {
    let h = header(path, bytes).to_lowercase();
    MARKERS.iter().any(|m| h.contains(m))
}

#[cfg(test)]
mod tests {
    //! The corpus: every case the record's review rounds raised, each with the outcome the rule gives it; and the
    //! machine-read markers and table of comment syntax of the record and of the book's trust chapter, held equal to
    //! [`super::MARKERS`] and [`super::TABLE`].

    use super::marked;

    #[test]
    fn the_corpus() {
        let licence = "// licence text, one of many lines\n".repeat(30);
        let long = format!("{licence}// @generated\nfn f() {{}}\n");
        let cases: &[(&str, &[u8], bool, &str)] = &[
            ("api/x.pb.go", b"// Code generated by protoc-gen-go. DO NOT EDIT.\npackage api\n", true, "the extension follows the last dot"),
            ("MAKEFILE", b"# generated by cmake\nall:\n", false, "a name is matched exactly, in its case"),
            (".md", b"<!-- generated by x -->\n", false, "a leading `.` opens no extension: `.md` has none, and no syntax"),
            ("x.rs", "\u{3000}// @generated\n".as_bytes(), true, "the header skips Unicode's whitespace"),
            ("x.rs", b"<?xml version=\"1.0\"?>\n// @generated\n", false, "the XML declaration is skipped in `<!--` files alone"),
            ("x.c", b"/* generated by x", true, "an unclosed C block runs to the end"),
            ("x.css", b"/* generated by x", true, "an unclosed CSS block runs to the end"),
            ("x.html", b"<!-- generated by x", true, "an unclosed `<!--` runs to the end"),
            ("x.kt", b"#!/x\n// @generated\n", false, "Rust's shebang rule is `.rs`'s alone"),
            ("NOTES", b"# generated by x\n#!/bin/sh\n", false, "an extensionless file's `#` line is no `#!`, nor a later `#!`"),
            ("src/x.rs", b"#!/usr/bin/env x\n// @generated\n", true, "the path's file name decides Rust's rule, not its directory"),
            ("x.xml", b"\n<?xml version=\"1.0\"?>\n<!-- generated by x -->\n", true, "the XML declaration after whitespace"),
            ("x.xml", "\u{3000}<?xml?>\n<!-- generated by x -->\n".as_bytes(), true, "Unicode's whitespace before the declaration"),
            ("x.xml", "<?xml\u{3000}?>\n<!-- generated by x -->\n".as_bytes(), true, "Unicode's whitespace after `<?xml`"),
            ("x.rs", b"#! /* @generated", true, "an unclosed block in the look-ahead runs to the end: a shebang"),
            ("x.md", b"\n", false, "a `<!--` file of whitespace alone"),
            ("x.c", b"/**\n * generated by x\n */\n", true, "a lone `*` inside a block is its text"),
            ("x.html", b"<!DOCTYPE html>\n<!-- generated by x -->\n", false, "`<!DOCTYPE` is no comment"),
            ("x.sql", b"-x\n-- generated by y\n", false, "a lone `-` opens no `--` comment"),
            ("crates/x/Makefile", b"# generated by x\nall:\n", true, "a name is the path's last component"),
            ("a.b/run", b"#!/bin/sh\n# generated by x\n", true, "a dotted directory gives no extension"),
            ("d/.md", b"<!-- generated by x -->\n", false, "a dotfile under a directory has no extension"),
            ("x.mjs", b"// generated by x\n", false, "an extension is matched whole: `.mjs` is not `js`"),
            (".gitlab-ci.yml", b"# generated by x\n", true, "a dotfile's extension follows its last `.`: `.gitlab-ci.yml`'s is `yml`"),
            ("x.rs", "\u{feff}#!/usr/bin/env x\n// @generated\n".as_bytes(), true, "a byte-order mark is dropped before Rust's shebang rule"),
            ("x.rs", b" #!/x\n// @generated\n", false, "a Rust shebang is `#!` at the very start, not after whitespace"),
            ("scripts/foo", b" #!/bin/sh\n# generated by x\n", false, "the extensionless rule's `#!` is at the very start"),
            ("x.xml", b"<?xml version=\"1.0\" encoding=\"do not edit\"?>\n<p/>\n", false, "the declaration's own text is no header"),
            ("foo.bar.", b"#!/bin/sh\n# generated by x\n", true, "a trailing dot is no extension, whatever comes before it"),
            ("X.RS", b"#!/usr/bin/env x\n// @generated\n", true, "Rust's rule by its extension in any case"),
            ("x.rs", b"#[allow(x)]\n// @generated\n", false, "an outer attribute is code: `#` without `!` is no shebang"),
            ("x.xml", b"<?xmx ?>\n<!-- generated by x -->\n", false, "the declaration is `<?xml`, whole"),
            ("x.c", b"/x generated by y */\n", false, "a lone `/` opens no block"),
            ("x.rs", b"/* a / b */\nfn f() {}\n// @generated\n", false, "a lone `/` in a Rust block opens no nested one"),
            ("x.css", b"/* a * generated by x */\n", true, "a lone `*` inside a CSS block is its text"),
            ("x.html", b"<!-x generated by y -->\n", false, "`<!-` opens no comment"),
            ("x.html", b"<!-- a -- b --><!-- generated by x -->\n", true, "a `<!--` block closes at `-->`, not at `--`"),
            ("x.xml", b"<?xml version=\"1.0\"\n<!-- generated by x -->\n", false, "an unclosed declaration runs to the end"),
            ("x.xml", b"<?xml?><!-- generated by x -->\n", true, "a comment straight after the declaration"),
            ("x.c", b"/*generated by x*/\n", true, "a block's text starts right after its `/*`"),
            ("x.c", b"/*/ generated by x */\n", true, "`/*/` opens a block"),
            ("x.c", b"/* x *//* @generated */\n", true, "a block straight after a block's close"),
            ("x.c", b"/* x */* generated by y\n", false, "a block closes at its `*/`, and a lone `*` after it is code"),
            ("x.rs", b"/* a /* b */ c */\nfn f() {}\n// @generated\n", false, "a nested block closes at its own `*/`"),
            ("x.rs", b"/* auto/**/-generated */\n", true, "a nested block's `/*` and `*/` leave the header's text"),
            ("x.rs", b"/* /* auto*/-generated */\n", true, "a nested block's `*/` leaves the header's text"),
            ("x.rs", b"/* x /*@generated */ */\n", true, "a nested block's text starts right after its `/*`"),
            ("x.rs", b"/* x /*/ y */ */\n// @generated\n", true, "`/*/` opens a nested block"),
            ("x.css", b"/*generated by x*/\n", true, "a CSS block's text starts right after its `/*`"),
            ("x.css", b"/*/ generated by x */\n", true, "`/*/` opens a CSS block"),
            ("x.css", b"/* x */\nbody {}\n/* generated by y */\n", false, "a CSS block closes at its `*/`"),
            ("x.css", b"/* x *//* generated by y */\n", true, "a CSS block straight after another"),
            ("x.css", b"/* x */* generated by y\n", false, "a CSS block's lone `*` after it is code"),
            ("x.html", b"<!--generated by x-->\n", true, "a `<!--` block's text starts right after it"),
            ("x.html", b"<!--> generated by x\n", true, "`-->` is sought after the opener, so `<!-->` opens a comment"),
            ("x.html", b"<!---> generated by x\n", true, "`-->` is sought after the opener's four characters: `<!--->` opens a comment"),
            ("x.html", b"<!-- x -->\n<p>\n<!-- generated by y -->\n", false, "a `<!--` block closes at its `-->`"),
            ("x.html", b"<!-- x --><!-- generated by y -->\n", true, "a `<!--` block straight after another"),
            ("x.c", b"// auto\n/*-generated */\n", false, "a line comment ends its line of the header: no marker across it"),
            ("x.c", b"/* auto*//*-generated */\n", false, "a block ends its line of the header"),
            ("x.css", b"/* auto*//*-generated */\n", false, "a CSS block ends its line of the header"),
            ("x.html", b"<!-- auto--><!---generated -->\n", false, "a `<!--` block ends its line of the header"),
            ("x.rs", b"#!/x auto\n/*-generated */\n", false, "a Rust shebang ends its line of the header"),
            ("x.rs", b"#!/usr/bin/env x // @generated", true, "a Rust shebang at the end of the file"),
            ("x.rs", b"#!/usr/bin/env x\nfn f() {}\n// @generated\n", false, "a Rust shebang ends at its line feed, the body after it"),
            (
                "x.rs",
                b"// This file was automatically generated\nfn f() {}\n",
                true,
                "the marker `automatically generated`",
            ),
            (
                "x.txt",
                b"#!/bin/sh\n# generated by x\n",
                false,
                "an extension the table lacks: no shebang rule",
            ),
            (
                "x.xml",
                b"<?xml?>\n<!-- generated by x -->\n",
                true,
                "a declaration closed by `?` at once",
            ),
            (
                "x.rs",
                "#!\t[allow(x)]\n// @generated\n".as_bytes(),
                false,
                "rustc skips a tab before `[`",
            ),
            (
                "x.rs",
                "#!\u{b}[allow(x)]\n// @generated\n".as_bytes(),
                false,
                "rustc skips a vertical tab before `[`",
            ),
            (
                "x.rs",
                "#!\u{c}[allow(x)]\n// @generated\n".as_bytes(),
                false,
                "rustc skips a form feed before `[`",
            ),
            (
                "x.rs",
                "#!\r[allow(x)]\n// @generated\n".as_bytes(),
                false,
                "rustc skips a carriage return before `[`",
            ),
            (
                "x.rs",
                "#!\u{85}[allow(x)]\n// @generated\n".as_bytes(),
                false,
                "rustc skips U+0085 before `[`",
            ),
            (
                "x.rs",
                "#!\u{200f}[allow(x)]\n// @generated\n".as_bytes(),
                false,
                "rustc skips U+200F before `[`",
            ),
            (
                "x.rs",
                "#!\u{2028}[allow(x)]\n// @generated\n".as_bytes(),
                false,
                "rustc skips U+2028 before `[`",
            ),
            (
                "x.rs",
                "#!\u{2029}[allow(x)]\n// @generated\n".as_bytes(),
                false,
                "rustc skips U+2029 before `[`",
            ),
            (
                "x.xml",
                b"<!-- generated by x -->\n<a>\xe9</a>\n",
                true,
                "an invalid byte after a clean header",
            ),
            (
                "x.rs",
                b"#! //! @generated\n[allow(x)]\n",
                true,
                "an inner line doc comment ends the look-ahead too",
            ),
            (
                "x.rs",
                b"#! // c\r[allow(x)]\n// @generated\n",
                true,
                "the look-ahead's line comment ends at a line feed",
            ),
            (
                ".rs",
                b"#!/bin/sh\rx\n# generated by x\n",
                false,
                "a file named `.rs` is a dotfile, read by its shebang as `#`",
            ),
            (
                "x.rs",
                b"// @generated by gen.sh\nfn f() {}\n",
                true,
                "a line comment",
            ),
            (
                "x.rs",
                "\u{feff}// @generated\nfn f() {}\n".as_bytes(),
                true,
                "a byte-order mark is dropped",
            ),
            (
                "x.rs",
                b"// Code generated by x. DO NOT EDIT.\r\nfn f() {}\r\n",
                true,
                "CRLF line endings",
            ),
            (
                "x.rs",
                b"/*\n   Code generated by scripts/gen.sh. DO NOT EDIT.\n*/\nfn f() {}\n",
                true,
                "a block comment's inner line",
            ),
            (
                "x.rs",
                long.as_bytes(),
                true,
                "a marker below a long licence comment",
            ),
            (
                "x.rs",
                b"fn f() {} // @generated\n",
                false,
                "a trailing comment on a code line",
            ),
            (
                "x.rs",
                b"const S: &str = \"generated by archogen\";\n",
                false,
                "a string",
            ),
            (
                "x.rs",
                b"fn f() {}\n// @generated\n",
                false,
                "a body marker",
            ),
            (
                "t.bin",
                &[0xff, 0xfe, 0x00, 0x40, 0x67],
                false,
                "a binary file: no comment syntax",
            ),
            (
                "x.rs",
                b"// \xff generated by x\n",
                true,
                "an invalid byte is read as U+FFFD, the marker kept",
            ),
            (
                "x.rs",
                b"#![allow(dead_code)]\n// @generated\n",
                false,
                "an attribute is code and ends the header",
            ),
            (
                "x.rs",
                b"# [derive(Debug)]\n// @generated\n",
                false,
                "a spaced attribute too",
            ),
            (
                "x.rs",
                b"#!/usr/bin/env run-cargo-script\n// @generated\n",
                true,
                "a shebang in Rust",
            ),
            (
                "x.sh",
                b"#!/bin/sh\n# generated by gen.py\necho\n",
                true,
                "a shebang and a hash comment",
            ),
            (
                "x.rs",
                b"/* outer /* inner */ still a comment: @generated */\nfn f() {}\n",
                true,
                "Rust's blocks nest",
            ),
            (
                "x.c",
                b"/* a /* b */ code @generated */\nint x;\n",
                false,
                "C's close at the first */",
            ),
            (
                "x.rs",
                b"/* x */ fn f() {} // @generated\n",
                false,
                "code after a block on its line",
            ),
            (
                "x.rs",
                b"// see /* no block opens here\n@generated\n",
                false,
                "a /* inside a line comment opens nothing",
            ),
            (
                "x.md",
                b"# Title\n<!-- generated by x -->\n",
                false,
                "a Markdown heading is content",
            ),
            (
                "x.md",
                b"<!-- generated by x -->\n# Title\n",
                true,
                "an HTML comment first",
            ),
            (
                "x.h",
                b"#ifndef X\n// generated by y\n",
                false,
                "a preprocessor line is code in C",
            ),
            (
                "x.csv",
                b"# generated by x\n1,2\n",
                false,
                "a CSV has no comment syntax",
            ),
            (
                "x.eadl",
                b"; generated by the tool\n(defblock b)\n",
                true,
                "an eADL comment",
            ),
            ("x.rs", b"// AUTO-GENERATED file\n", true, "any case"),
            ("x.rs", b"// Do Not Edit\n", true, "any case, do not edit"),
            ("x.rs", b"", false, "an empty file"),
            ("x.rs", b"  \n\n", false, "whitespace alone"),
            (
                "x.rs",
                b"// @generated",
                true,
                "a header that is the whole file, no newline",
            ),
            (
                "Makefile",
                b"# generated by cmake\nall:\n",
                true,
                "a Makefile, by its name",
            ),
            (
                "x.py",
                b"\n\n# autogenerated from schema.json\nimport x\n",
                true,
                "blank lines before the header",
            ),
            (
                "x.rs",
                b"#! [allow(dead_code)]\n// @generated\n",
                false,
                "a spaced inner attribute is no shebang",
            ),
            (
                "x.rs",
                b"#! /* c */ [allow(x)]\n// @generated\n",
                false,
                "nor one after a comment",
            ),
            (
                "x.kt",
                b"/* a /* b */ @generated */\nclass X\n",
                true,
                "Kotlin's blocks nest",
            ),
            (
                "x.py",
                b"# h\rimport x\r# @generated\r",
                false,
                "a CR ends a line, so a body marker stays in the body",
            ),
            (
                "x.xml",
                b"<?xml version=\"1.0\"?>\n<!-- Generated by x -->\n<a/>\n",
                true,
                "an XML declaration first",
            ),
            (
                "scripts/foo",
                b"#!/bin/sh\n# generated by gen.py\necho\n",
                true,
                "an extensionless script by its shebang",
            ),
            (
                "scripts/foo",
                b"generated by nothing\n",
                false,
                "an extensionless file with no shebang",
            ),
            (
                "x.rs",
                b"/* licence\nfn f() {} // @generated\n",
                true,
                "an unclosed block runs to the end",
            ),
            (
                "x.rs",
                b"//! The S0 table, generated by gen.sh.\npub const T: u8 = 1;\n",
                true,
                "an inner doc comment is a comment",
            ),
            ("X.RS", b"// @generated\n", true, "an extension in capitals"),
            (
                "x.rs",
                b"#! /* a /* b */ c */ [allow(dead_code)]\n// @generated\nfn f() {}\n",
                false,
                "the look-ahead nests",
            ),
            (
                "x.rs",
                b"#! /*! d */ [allow(dead_code)]\n// @generated\nfn f() {}\n",
                true,
                "a doc comment ends the look-ahead: a shebang",
            ),
            (
                "x.rs",
                b"#! /// @generated\n[allow(x)]\n",
                true,
                "a line doc comment ends the look-ahead: a shebang",
            ),
            (
                "x.rs",
                b"#! // c\n[allow(dead_code)]\n// @generated\n",
                false,
                "a plain line comment is skipped",
            ),
            (
                "x.adb",
                b"-- generated by gnatprep\nprocedure P is\n",
                true,
                "Ada's body file",
            ),
            ("x.r", b"# generated by roxygen2\nf <- 1\n", true, "R"),
            (
                "CMakeLists.txt",
                b"# generated by a template\nproject(x)\n",
                true,
                "CMake by its name",
            ),
            (
                "x.css",
                b"// generated by x\na {}\n",
                false,
                "CSS has no line comments",
            ),
            (
                "x.css",
                b"/* generated by x */\na {}\n",
                true,
                "a CSS block comment",
            ),
            (
                "x.html",
                b"<?php echo 1; ?>\n<!-- generated by x -->\n",
                false,
                "a PHP instruction is content",
            ),
            (
                "x.xml",
                b"<?xml-stylesheet href=\"a\"?>\n<!-- generated by x -->\n",
                false,
                "a stylesheet instruction is content",
            ),
            (
                "x.xml",
                b"<?xml version=\"1.0\"?>\n<?xml-stylesheet href=\"a\"?>\n<!-- generated by x -->\n",
                false,
                "the declaration alone is skipped",
            ),
            (
                "scripts/foo",
                "\u{feff}#!/bin/sh\n# generated by x\n".as_bytes(),
                true,
                "a byte-order mark before an extensionless shebang",
            ),
            (
                ".env",
                b"# generated by x\nA=1\n",
                true,
                "a dotfile read by its name",
            ),
            (
                ".envrc",
                b"# generated by x\n",
                false,
                "a dotfile neither named nor with a shebang",
            ),
            (
                "x.rs",
                "#!\u{200e}[allow(x)]\n// @generated\n".as_bytes(),
                false,
                "rustc skips U+200E before `[`",
            ),
            (
                "x.rs",
                "#!\u{a0}[allow(x)]\n// @generated\n".as_bytes(),
                true,
                "but not U+00A0: a shebang",
            ),
            (
                "x.rs",
                b"#!/usr/bin/x\rfn f() {}\n// @generated\n",
                true,
                "a Rust shebang ends at a line feed, not a carriage return",
            ),
            (
                "é.md",
                b"<!-- generated by x -->\n# T\n",
                true,
                "a name opening with a multi-byte character keeps its extension",
            ),
            (
                "foo.",
                b"#!/bin/sh\n# generated by x\n",
                true,
                "a trailing dot is no extension: extensionless, by its shebang",
            ),
            (
                "foo.",
                b"# generated by x\n",
                false,
                "a trailing dot, no shebang: no syntax",
            ),
            (
                "x.rs",
                b"#! //// c\n[allow(dead_code)]\n// @generated\n",
                false,
                "`////` is a plain comment: an attribute",
            ),
            (
                "x.rs",
                b"#! /**/ [allow(dead_code)]\n// @generated\n",
                false,
                "`/**/` is a plain comment: an attribute",
            ),
            (
                "x.rs",
                b"#! /*** c */ [allow(dead_code)]\n// @generated\n",
                false,
                "`/***` is a plain comment: an attribute",
            ),
            (
                "x.rs",
                b"// the code generated by the emitter is checked here\nfn f() {}\n",
                true,
                "a marker phrase in prose marks: the repair is rewording",
            ),
            (
                "x.py",
                b"#!/usr/bin/python\rimport x\r# @generated\r",
                false,
                "a `#` language's shebang line ends at a carriage return too",
            ),
        ];
        for (path, bytes, want, why) in cases {
            assert_eq!(marked(path, bytes), *want, "{why}: {path}");
        }
    }

    #[test]
    fn the_shebang_rule_is_rustc_s() {
        // The record's §3: what rustc does with a `#!` line is a fixture's result, scored three ways against a control
        // whose unused function draws a warning. Read as a shebang, the line is skipped: the warning stands, or, where
        // a line follows that is no item, rustc refuses it ("expected item, found `[`"). Read as an inner attribute,
        // `allow(dead_code)` applies and the file compiles silently. Each case names the outcome rustc gives, and
        // `rust_shebang` must say "shebang" exactly when that outcome is not the silent one.
        #[derive(Debug, PartialEq)]
        enum Said {
            Warning,
            Silent,
            Refused,
        }
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .unwrap()
            .to_path_buf();
        // The pinned toolchain, and no other: `cargo +other test` would measure another rustc.
        let pin = std::fs::read_to_string(root.join("rust-toolchain.toml")).unwrap();
        let channel = pin
            .lines()
            .find_map(|l| l.trim().strip_prefix("channel"))
            .and_then(|l| l.split('"').nth(1))
            .expect("rust-toolchain.toml names its channel")
            .to_owned();
        let version = std::process::Command::new("rustc")
            .arg("-V")
            .current_dir(&root)
            .output()
            .expect("rustc");
        let version = String::from_utf8_lossy(&version.stdout);
        assert!(
            version.starts_with(&format!("rustc {channel} ")),
            "the fixture measures the pinned rustc {channel}, not {version}"
        );
        let dir = root.join("target/generated-header-rustc");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let attr = "[allow(dead_code)]";
        let cases: Vec<(String, Said)> = vec![
            (format!("#! {attr}"), Said::Silent),
            (format!("#! /* c */ {attr}"), Said::Silent),
            (format!("#! /* a /* b */ c */ {attr}"), Said::Silent),
            (format!("#! // c\n{attr}"), Said::Silent),
            (format!("#! //// c\n{attr}"), Said::Silent),
            (format!("#! /**/ {attr}"), Said::Silent),
            (format!("#! /*** c */ {attr}"), Said::Silent),
            (format!("#!\u{200e}{attr}"), Said::Silent),
            (format!("#!\t{attr}"), Said::Silent),
            (format!("#!\u{b}{attr}"), Said::Silent),
            (format!("#!\u{c}{attr}"), Said::Silent),
            (format!("#!\r{attr}"), Said::Silent),
            (format!("#!\u{85}{attr}"), Said::Silent),
            (format!("#!\u{200f}{attr}"), Said::Silent),
            (format!("#!\u{2028}{attr}"), Said::Silent),
            (format!("#!\u{2029}{attr}"), Said::Silent),
            // The look-ahead's comments read a character at a time: a line comment whose line feed falls on an even
            // offset, a block opened by `/*/`, a nested block opened by `/*/`, and a nested `/**/`.
            (format!("#! //c\n{attr}"), Said::Silent),
            (format!("#! /*/ */ {attr}"), Said::Silent),
            (format!("#! /* /*/ */ */ {attr}"), Said::Silent),
            (format!("#! /* /**/ */ {attr}"), Said::Silent),
            // `[` straight after a block's close.
            (format!("#! /* c */{attr}"), Said::Silent),
            // A `/` that opens no comment ends the look-ahead, even before a `*/` and a `[`.
            (format!("#!/x */ {attr}"), Said::Warning),
            // A doc comment ends the look-ahead: the line is a shebang.
            (format!("#! /*! d */ {attr}"), Said::Warning),
            (format!("#! /** d */ {attr}"), Said::Warning),
            (format!("#! //! d\n{attr}"), Said::Refused),
            (format!("#! /// d\n{attr}"), Said::Refused),
            (format!("#!\u{a0}{attr}"), Said::Warning),
            ("#!/usr/bin/env run-cargo-script".to_owned(), Said::Warning),
            // The look-ahead's line comment ends at a line feed, so `[` after a carriage return is inside it.
            (format!("#! // c\r{attr}"), Said::Warning),
            // A shebang ends at a line feed: through the carriage return, so the attribute after it is the shebang's.
            (
                "#!/usr/bin/x\r#![allow(dead_code)]".to_owned(),
                Said::Warning,
            ),
        ];
        let compile = |n: usize, head: &str| {
            let file = dir.join(format!("c{n}.rs"));
            std::fs::write(&file, format!("{head}\nfn unused() {{}}\nfn main() {{}}\n")).unwrap();
            let out = std::process::Command::new("rustc")
                .args(["--edition", "2021", "--emit=metadata", "-o"])
                .arg(dir.join(format!("c{n}.rmeta")))
                .arg(&file)
                .current_dir(&root)
                .output()
                .expect("rustc");
            let said = String::from_utf8_lossy(&out.stderr).into_owned();
            let outcome = if !out.status.success() {
                assert!(
                    said.contains("expected item, found `[`"),
                    "refused for another reason: {said}"
                );
                Said::Refused
            } else if said.contains("never used") {
                Said::Warning
            } else {
                Said::Silent
            };
            (outcome, said)
        };
        let (control, said) = compile(0, "");
        assert_eq!(
            control,
            Said::Warning,
            "the control draws its warning: {said}"
        );
        for (n, (head, want)) in cases.iter().enumerate() {
            let (got, said) = compile(n + 1, head);
            assert_eq!(&got, want, "rustc on {head:?}: {said}");
            let chars: Vec<char> = head.chars().collect();
            assert_eq!(
                super::rust_shebang(&chars),
                *want != Said::Silent,
                "rust_shebang on {head:?}"
            );
        }
    }

    /// The record, then the book's trust chapter, which states the markers and the table of comment syntax again
    /// (`M3.6.6.3`): each copy is held equal to the code, so neither drifts from it.
    const DOCUMENTS: [&str; 2] = [
        "docs/specs/trust/decision_trust-generated-sources.md",
        "docs/book/src/trust.md",
    ];

    fn document(path: &str) -> String {
        std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("..")
                .join(path),
        )
        .unwrap_or_else(|e| panic!("{path}: {e}"))
    }

    /// A machine-read block of a document: the lines after `<!-- machine-read: NAME -->` up to the first blank one.
    fn block(path: &str, name: &str) -> Vec<String> {
        document(path)
            .split(&format!("<!-- machine-read: {name} -->"))
            .nth(1)
            .unwrap_or_else(|| panic!("{path}'s machine-read `{name}`"))
            .lines()
            .skip(1)
            .take_while(|l| !l.trim().is_empty())
            .map(str::to_owned)
            .collect()
    }

    fn record_block(name: &str) -> Vec<String> {
        block(DOCUMENTS[0], name)
    }

    #[test]
    fn the_record_s_markers_are_the_code_s() {
        let mut code: Vec<String> = super::MARKERS.iter().map(|m| (*m).to_owned()).collect();
        code.sort();
        for doc in DOCUMENTS {
            let mut listed: Vec<String> = block(doc, "markers")
                .join(" ")
                .split('`')
                .skip(1)
                .step_by(2)
                .map(str::to_owned)
                .collect();
            listed.sort();
            assert_eq!(
                listed, code,
                "{doc}'s markers and generated_header::MARKERS"
            );
        }
    }

    #[test]
    fn every_rule_the_record_states_has_a_catalogued_mutation_and_every_mutation_a_rule() {
        // The record's §3 maps each rule of the recogniser to the `gh-…` mutation that breaks it; each must be in
        // `xtask/mutations.txt`, aimed at this file and expected killed — `cargo xtask mutate` runs it — and every
        // such entry must be one the record lists.
        let rows = record_block("recogniser-mutations");
        let listed: std::collections::BTreeSet<String> = rows
            .iter()
            .skip(2)
            .filter_map(|r| r.split('|').nth(2))
            .map(|c| c.trim().trim_matches('`').to_owned())
            .collect();
        assert!(!listed.is_empty(), "the record lists its rules' mutations");
        let catalog = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("mutations.txt"),
        )
        .expect("the catalog");
        let mut aimed = std::collections::BTreeSet::new();
        for entry in catalog.split("\nmutation ").skip(1) {
            let name = entry.lines().next().unwrap_or("").trim().to_owned();
            if entry
                .lines()
                .any(|l| l == "file xtask/src/generated_header.rs")
            {
                assert!(
                    entry.lines().any(|l| l == "expect killed"),
                    "{name} is expected killed"
                );
                aimed.insert(name);
            }
        }
        assert_eq!(
            listed, aimed,
            "the record's rule-to-mutation table and the catalogue's entries for this file"
        );
    }

    #[test]
    fn the_record_s_table_of_comment_syntax_is_the_code_s() {
        for doc in DOCUMENTS {
            table_is_the_code_s(doc);
        }
    }

    fn table_is_the_code_s(doc: &str) {
        use super::{Syntax, TABLE};
        let text = document(doc);
        let table = text
            .split("<!-- machine-read: comment-syntax -->")
            .nth(1)
            .unwrap_or_else(|| panic!("{doc}'s machine-read table"));
        let words = |cell: &str| -> Vec<String> {
            let mut w: Vec<String> = cell
                .split('`')
                .skip(1)
                .step_by(2)
                .map(str::to_owned)
                .collect();
            w.sort();
            w
        };
        let mut rows = Vec::new();
        for line in table.lines().skip(3) {
            let cells: Vec<&str> = line.split('|').map(str::trim).collect();
            if cells.len() < 5 {
                break;
            }
            let syn = match cells[1] {
                "`//` and `/* */`, nesting" => Syntax::Slash { nests: true },
                "`//` and `/* */`" => Syntax::Slash { nests: false },
                "`/* */`" => Syntax::Block,
                "`#`" => Syntax::Hash,
                "`;`" => Syntax::Semicolon,
                "`--`" => Syntax::Dash,
                "`<!-- -->`" => Syntax::Angle,
                other => panic!("a syntax the code does not name: {other}"),
            };
            rows.push((syn, words(cells[2]), words(cells[3])));
        }
        let code: Vec<(Syntax, Vec<String>, Vec<String>)> = TABLE
            .iter()
            .map(|(syn, exts, names)| {
                let sorted = |xs: &[&str]| {
                    let mut v: Vec<String> = xs.iter().map(|x| (*x).to_owned()).collect();
                    v.sort();
                    v
                };
                (*syn, sorted(exts), sorted(names))
            })
            .collect();
        assert_eq!(rows, code, "{doc}'s table and generated_header::TABLE");
    }
}
